//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace SPMWebApp.SuperAdmin {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SuperAdminSoap", Namespace="http://tempuri.org/")]
    public partial class SuperAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SuperAdmin_GetByFiltersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuperAdmin_GetddlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuperAdmin_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuperAdmin_InsertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SuperAdmin() {
            this.Url = global::SPMWebApp.Properties.Settings.Default.SPMWebApp_SuperAdmin_SuperAdmin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SuperAdmin_GetByFiltersCompletedEventHandler SuperAdmin_GetByFiltersCompleted;
        
        /// <remarks/>
        public event SuperAdmin_GetddlCompletedEventHandler SuperAdmin_GetddlCompleted;
        
        /// <remarks/>
        public event SuperAdmin_DeleteCompletedEventHandler SuperAdmin_DeleteCompleted;
        
        /// <remarks/>
        public event SuperAdmin_InsertCompletedEventHandler SuperAdmin_InsertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuperAdmin_GetByFilters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SuperAdmin_GetByFilters(string UserID, string AEGroup, int Start, int PageLength, string dbConnectionStr) {
            object[] results = this.Invoke("SuperAdmin_GetByFilters", new object[] {
                        UserID,
                        AEGroup,
                        Start,
                        PageLength,
                        dbConnectionStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SuperAdmin_GetByFiltersAsync(string UserID, string AEGroup, int Start, int PageLength, string dbConnectionStr) {
            this.SuperAdmin_GetByFiltersAsync(UserID, AEGroup, Start, PageLength, dbConnectionStr, null);
        }
        
        /// <remarks/>
        public void SuperAdmin_GetByFiltersAsync(string UserID, string AEGroup, int Start, int PageLength, string dbConnectionStr, object userState) {
            if ((this.SuperAdmin_GetByFiltersOperationCompleted == null)) {
                this.SuperAdmin_GetByFiltersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuperAdmin_GetByFiltersOperationCompleted);
            }
            this.InvokeAsync("SuperAdmin_GetByFilters", new object[] {
                        UserID,
                        AEGroup,
                        Start,
                        PageLength,
                        dbConnectionStr}, this.SuperAdmin_GetByFiltersOperationCompleted, userState);
        }
        
        private void OnSuperAdmin_GetByFiltersOperationCompleted(object arg) {
            if ((this.SuperAdmin_GetByFiltersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuperAdmin_GetByFiltersCompleted(this, new SuperAdmin_GetByFiltersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuperAdmin_Getddl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SuperAdmin_Getddl(string UserID, string AEGroup, string rdbtnUserIDOption, string rdbtnAEGroupOption, string dbConnectionStr) {
            object[] results = this.Invoke("SuperAdmin_Getddl", new object[] {
                        UserID,
                        AEGroup,
                        rdbtnUserIDOption,
                        rdbtnAEGroupOption,
                        dbConnectionStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SuperAdmin_GetddlAsync(string UserID, string AEGroup, string rdbtnUserIDOption, string rdbtnAEGroupOption, string dbConnectionStr) {
            this.SuperAdmin_GetddlAsync(UserID, AEGroup, rdbtnUserIDOption, rdbtnAEGroupOption, dbConnectionStr, null);
        }
        
        /// <remarks/>
        public void SuperAdmin_GetddlAsync(string UserID, string AEGroup, string rdbtnUserIDOption, string rdbtnAEGroupOption, string dbConnectionStr, object userState) {
            if ((this.SuperAdmin_GetddlOperationCompleted == null)) {
                this.SuperAdmin_GetddlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuperAdmin_GetddlOperationCompleted);
            }
            this.InvokeAsync("SuperAdmin_Getddl", new object[] {
                        UserID,
                        AEGroup,
                        rdbtnUserIDOption,
                        rdbtnAEGroupOption,
                        dbConnectionStr}, this.SuperAdmin_GetddlOperationCompleted, userState);
        }
        
        private void OnSuperAdmin_GetddlOperationCompleted(object arg) {
            if ((this.SuperAdmin_GetddlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuperAdmin_GetddlCompleted(this, new SuperAdmin_GetddlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuperAdmin_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SuperAdmin_Delete(string UserID, string AEGroup, string dbConnectionStr) {
            object[] results = this.Invoke("SuperAdmin_Delete", new object[] {
                        UserID,
                        AEGroup,
                        dbConnectionStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SuperAdmin_DeleteAsync(string UserID, string AEGroup, string dbConnectionStr) {
            this.SuperAdmin_DeleteAsync(UserID, AEGroup, dbConnectionStr, null);
        }
        
        /// <remarks/>
        public void SuperAdmin_DeleteAsync(string UserID, string AEGroup, string dbConnectionStr, object userState) {
            if ((this.SuperAdmin_DeleteOperationCompleted == null)) {
                this.SuperAdmin_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuperAdmin_DeleteOperationCompleted);
            }
            this.InvokeAsync("SuperAdmin_Delete", new object[] {
                        UserID,
                        AEGroup,
                        dbConnectionStr}, this.SuperAdmin_DeleteOperationCompleted, userState);
        }
        
        private void OnSuperAdmin_DeleteOperationCompleted(object arg) {
            if ((this.SuperAdmin_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuperAdmin_DeleteCompleted(this, new SuperAdmin_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuperAdmin_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SuperAdmin_Insert(string UserID, string AEGroup, string dbConnectionStr) {
            object[] results = this.Invoke("SuperAdmin_Insert", new object[] {
                        UserID,
                        AEGroup,
                        dbConnectionStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SuperAdmin_InsertAsync(string UserID, string AEGroup, string dbConnectionStr) {
            this.SuperAdmin_InsertAsync(UserID, AEGroup, dbConnectionStr, null);
        }
        
        /// <remarks/>
        public void SuperAdmin_InsertAsync(string UserID, string AEGroup, string dbConnectionStr, object userState) {
            if ((this.SuperAdmin_InsertOperationCompleted == null)) {
                this.SuperAdmin_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuperAdmin_InsertOperationCompleted);
            }
            this.InvokeAsync("SuperAdmin_Insert", new object[] {
                        UserID,
                        AEGroup,
                        dbConnectionStr}, this.SuperAdmin_InsertOperationCompleted, userState);
        }
        
        private void OnSuperAdmin_InsertOperationCompleted(object arg) {
            if ((this.SuperAdmin_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuperAdmin_InsertCompleted(this, new SuperAdmin_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SuperAdmin_GetByFiltersCompletedEventHandler(object sender, SuperAdmin_GetByFiltersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperAdmin_GetByFiltersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuperAdmin_GetByFiltersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SuperAdmin_GetddlCompletedEventHandler(object sender, SuperAdmin_GetddlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperAdmin_GetddlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuperAdmin_GetddlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SuperAdmin_DeleteCompletedEventHandler(object sender, SuperAdmin_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperAdmin_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuperAdmin_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SuperAdmin_InsertCompletedEventHandler(object sender, SuperAdmin_InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperAdmin_InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuperAdmin_InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591